'use strict';

/**
 * @file Unified world state restoration from a snapshot.
 *
 * Responsibility:
 *   Single function `restoreState` that overwrites the server DB
 *   and env in-place from a snapshot. Used by both rewind (from
 *   server ring buffer) and load (from disk file).
 *
 * **Replaces:** `rewindToTick` (tools/viewer/rewind.js) and
 *   `restoreFromDump` (tools/viewer/dbDump.js) — both become thin
 *   wrappers that assemble a snapshot object and call `restoreState`.
 *
 * @module lib/orchestration/restoreState
 */

const { getBotMemory } = require('../builders/memory');

/**
 * @typedef {import('../runtime/storageAdapter').StorageAdapter} StorageAdapter
 */

// ─── Utility ───────────────────────────────────────────────────────────────

/**
 * Strips LokiJS internal fields ($loki, meta) from a DB document.
 * These fields are auto-generated by LokiJS and must not be re-inserted
 * after a collection clear — otherwise duplicate-key errors occur.
 *
 * @param {Object} doc
 * @returns {Object} — shallow copy without LokiJS internals
 */
function stripLokiInternals(doc) {
    // eslint-disable-next-line no-unused-vars
    const { $loki, meta, ...clean } = doc;
    return clean;
}

/**
 * Returns true if the value is neither null nor undefined.
 * Used to distinguish "key absent" from "key present with falsy value"
 * (e.g. empty array) for optional snapshot sections.
 *
 * @param {*} val
 * @returns {boolean}
 */
function isPresent(val) {
    // eslint-disable-next-line eqeqeq
    return val != null;
}

/**
 * Clears and repopulates a LokiJS collection.
 *
 * Uses `clear()` (full reset) instead of `removeWhere({})` because
 * `clear` resets internal ID counters, preventing duplicate-key errors
 * when re-inserting documents that previously existed in the collection.
 *
 * After refill, verifies the document count matches — throws if not,
 * preventing silent partial-restore corruption.
 *
 * @param {Object} collection — LokiJS collection proxy (RPC)
 * @param {Object[]} documents — documents to insert after clearing
 * @param {string} label — human-readable collection name for error messages
 * @returns {Promise<void>}
 * @throws {Error} if clear fails, any insert fails, or count mismatch after refill
 */
async function clearAndRefill(collection, documents, label) {
    // 1. Clear
    if (typeof collection.clear === 'function') {
        await collection.clear();
    } else {
        // Fallback for collections without clear()
        await collection.removeWhere({});
    }

    // 2. Insert with stripped LokiJS internals
    const cleanDocs = documents.map(stripLokiInternals);
    for (let i = 0; i < cleanDocs.length; i++) {
        try {
            await collection.insert(cleanDocs[i]);
        } catch (err) {
            throw new Error(`Failed to insert document ${i}/${cleanDocs.length} into ${label}: ${err.message || err}`);
        }
    }

    // 3. Verify count — prevent silent partial-restore corruption
    let allDocs;
    try {
        allDocs = await collection.find({});
    } catch (err) {
        throw new Error(`Failed to verify ${label} after refill: ${err.message || err}`);
    }
    if (!Array.isArray(allDocs) || allDocs.length !== cleanDocs.length) {
        const actual = Array.isArray(allDocs) ? allDocs.length : 'N/A';
        throw new Error(
            `Refill mismatch for ${label}: expected ${cleanDocs.length} docs, got ${actual}. ` +
                'The collection may be in a corrupted state.',
        );
    }
}

// ─── restoreState ──────────────────────────────────────────────────────────

/**
 * Restores world state from a snapshot.
 *
 * Steps:
 *   1. Read current gameTime (BEFORE overwriting — needed for truncation)
 *   2. Overwrite rooms.objects (clear + refill)
 *   3. Overwrite rooms.terrain (only if snapshot has terrain data)
 *   4. Overwrite rooms.flags (only if snapshot has flags data)
 *   5. Set gameTime in env
 *   6. Set Memory for each bot
 *   7. Set roomStatus and accessibleRooms
 *   8. Truncate future per-tick snapshots (sit:snap: > tick)
 *   9. Truncate roomHistory
 *  10. Update report.ticksRun (if extras.report)
 *
 * TODO(phase3-step6.3): Validate snapshot.version >= '2.0' for
 *   compatibility; currently any version is accepted silently.
 *
 * @param {StorageAdapter} adapter
 * @param {Object<string, {id:string}>} bots
 * @param {Object} snapshot — { version?, meta, db, env }
 * @param {Object} [extras]
 * @param {Object} [extras.report] — worker report to update ticksRun
 * @param {Object<string,Object>} [extras.memories] — per-bot Memory
 *   (from memoryHistory for rewind; if absent, uses snapshot.env.memory)
 * @returns {Promise<{tick:number, rooms:number, bots:number}>}
 */
async function restoreState(adapter, bots, snapshot, extras = {}) {
    const { db, env } = adapter;

    // 1. Read current gameTime BEFORE overwriting (needed for truncation)
    const currentTick = parseInt((await env.get(env.keys.GAMETIME)) || '0', 10);
    const targetTick = snapshot.env.gameTime;

    // 2. rooms.objects — always restore
    await clearAndRefill(db['rooms.objects'], snapshot.db['rooms.objects'], 'rooms.objects');

    // 3. terrain — only if snapshot HAS terrain data (rewind doesn't)
    //    Check key existence, not just truthiness: empty array = "clear terrain"
    if (db['rooms.terrain'] && isPresent(snapshot.db['rooms.terrain'])) {
        await clearAndRefill(db['rooms.terrain'], snapshot.db['rooms.terrain'], 'rooms.terrain');
    }

    // 4. flags — only if snapshot HAS flags data
    if (db['rooms.flags'] && isPresent(snapshot.db['rooms.flags'])) {
        await clearAndRefill(db['rooms.flags'], snapshot.db['rooms.flags'], 'rooms.flags');
    }

    // 5. gameTime
    await env.set(env.keys.GAMETIME, String(targetTick));

    // 6. Memory — extras.memories (rewind) takes priority over snapshot.env.memory (load)
    //    If neither has the bot, fall back to current memory (best-effort)
    for (const [username, bot] of Object.entries(bots)) {
        let mem = null;
        if (extras.memories && isPresent(extras.memories[username])) {
            mem = extras.memories[username];
        } else if (snapshot.env.memory && isPresent(snapshot.env.memory[username])) {
            mem = snapshot.env.memory[username];
        } else {
            try {
                mem = await getBotMemory(adapter, bot.id);
            } catch {
                /* no memory — leave null */
            }
        }
        if (mem !== undefined && mem !== null) {
            await env.set(env.keys.MEMORY + bot.id, JSON.stringify(mem));
        }
    }

    // 7. roomStatus + accessibleRooms (only if present in snapshot)
    if (snapshot.env.roomStatus) {
        await env.set(env.keys.ROOM_STATUS_DATA, JSON.stringify(snapshot.env.roomStatus));
    }
    if (snapshot.env.accessibleRooms) {
        await env.set(env.keys.ACCESSIBLE_ROOMS, JSON.stringify(snapshot.env.accessibleRooms));
    }

    // 8. Truncate future per-tick snapshots (ticks after target are gone)
    for (let i = targetTick + 1; i <= currentTick; i++) {
        try {
            await env.del('sit:snap:' + i);
        } catch {
            /* ignore — key may not exist */
        }
    }

    // 9. Truncate roomHistory
    for (const roomName of snapshot.meta.rooms) {
        try {
            await env.del(env.keys.ROOM_HISTORY + roomName);
        } catch {
            /* roomHistory may not exist — ignore */
        }
    }

    // 10. Update worker state
    if (extras.report) {
        extras.report.ticksRun = targetTick;
        extras.report.stopReason = null;
    }

    return {
        tick: targetTick,
        rooms: snapshot.meta.rooms.length,
        bots: Object.keys(bots).length,
    };
}

module.exports = { restoreState, clearAndRefill, stripLokiInternals };
