'use strict';

/**
 * @file Collects a full DB dump from the mockup server for snapshot
 *   save/load. Reads rooms.objects, rooms.terrain, rooms.flags, and
 *   relevant env keys (gameTime, memory, roomStatus).
 *
 * Responsibility:
 *   - `collectFullDump` — reads the full DB state and returns a snapshot object
 *   - `restoreFromDump` — overwrites the DB in-place from a saved snapshot
 *   - No worker restart needed — the mockup tick processor is stateless between ticks
 *
 * @module tools/viewer/dbDump
 */

const { getBotMemory } = require('../../lib/builders/memory');

/**
 * @typedef {import('../../lib/runtime/storageAdapter').StorageAdapter} StorageAdapter
 */

/**
 * Collects a full snapshot of the current DB state.
 *
 * Reads all rooms.objects, rooms.terrain, rooms.flags collections and
 * relevant env keys (gameTime, memory, roomStatus, accessibleRooms).
 * Bot Memory is collected per-bot via getBotMemory.
 *
 * @param {StorageAdapter} adapter
 * @param {Object<string, {id:string}>} bots — map of username → { id }
 * @param {Object<string, *>} roomStatus
 * @param {string} scenarioPath
 * @returns {Promise<Object>} — snapshot object ready for JSON serialization
 */
async function collectFullDump(adapter, bots, roomStatus, scenarioPath) {
    const { db, env } = adapter;

    // 1. DB collections
    const roomObjects = await db['rooms.objects'].find({});
    const roomTerrain = await db['rooms.terrain'].find({});
    const roomFlags = db['rooms.flags'] ? await db['rooms.flags'].find({}) : [];

    // 2. Env keys
    const gameTime = parseInt((await env.get(env.keys.GAMETIME)) || '0', 10);
    const roomStatusData = await env.get(env.keys.ROOM_STATUS_DATA);
    const accessibleRooms = await env.get(env.keys.ACCESSIBLE_ROOMS);

    // 3. Bot Memory
    /** @type {Object<string, *>} */
    const memory = {};
    for (const [username, bot] of Object.entries(bots)) {
        try {
            memory[username] = await getBotMemory(adapter, bot.id);
        } catch {
            memory[username] = {};
        }
    }

    return {
        meta: {
            scenario: scenarioPath,
            timestamp: new Date().toISOString(),
            tick: gameTime,
            bots: Object.keys(bots),
            rooms: Object.keys(roomStatus),
        },
        db: {
            'rooms.objects': roomObjects,
            'rooms.terrain': roomTerrain,
            'rooms.flags': roomFlags,
        },
        env: {
            gameTime,
            memory,
            roomStatus: roomStatusData ? JSON.parse(roomStatusData) : null,
            accessibleRooms: accessibleRooms ? JSON.parse(accessibleRooms) : null,
        },
    };
}

/**
 * Strips LokiJS internal fields ($loki, meta) from a DB document.
 * These fields are auto-generated by LokiJS and must not be re-inserted
 * after a collection clear — otherwise duplicate-key errors occur.
 *
 * @param {Object} doc
 * @returns {Object} — shallow copy without LokiJS internals
 */
function stripLokiInternals(doc) {
    // eslint-disable-next-line no-unused-vars
    const { $loki, meta, ...clean } = doc;
    return clean;
}

/**
 * Clears and repopulates a LokiJS collection.
 *
 * Uses `clear()` (full reset) instead of `removeWhere({})` because
 * `clear` resets internal ID counters, preventing duplicate-key errors
 * when re-inserting documents that previously existed in the collection.
 *
 * After refill, verifies the document count matches — throws if not,
 * preventing silent partial-restore corruption.
 *
 * @param {Object} collection — LokiJS collection proxy (RPC)
 * @param {Object[]} documents — documents to insert after clearing
 * @param {string} label — human-readable collection name for error messages
 * @returns {Promise<void>}
 * @throws {Error} if clear fails, any insert fails, or count mismatch after refill
 */
async function clearAndRefill(collection, documents, label) {
    // 1. Clear
    if (typeof collection.clear === 'function') {
        await collection.clear();
    } else {
        // Fallback for collections without clear()
        await collection.removeWhere({});
    }

    // 2. Insert with stripped LokiJS internals
    const cleanDocs = documents.map(stripLokiInternals);
    for (let i = 0; i < cleanDocs.length; i++) {
        try {
            await collection.insert(cleanDocs[i]);
        } catch (err) {
            throw new Error(`Failed to insert document ${i}/${cleanDocs.length} into ${label}: ${err.message || err}`);
        }
    }

    // 3. Verify count — prevent silent partial-restore corruption
    let allDocs;
    try {
        allDocs = await collection.find({});
    } catch (err) {
        throw new Error(`Failed to verify ${label} after refill: ${err.message || err}`);
    }
    if (!Array.isArray(allDocs) || allDocs.length !== cleanDocs.length) {
        const actual = Array.isArray(allDocs) ? allDocs.length : 'N/A';
        throw new Error(
            `Refill mismatch for ${label}: expected ${cleanDocs.length} docs, got ${actual}. ` +
                'The collection may be in a corrupted state.',
        );
    }
}

/**
 * Restores the DB from a snapshot, overwriting the current state.
 * Does NOT restart the server — overwrites in-place.
 *
 * Steps:
 *   1. Clear and restore rooms.objects
 *   2. Restore rooms.terrain (if collection exists)
 *   3. Restore rooms.flags (if collection exists)
 *   4. Set env gameTime
 *   5. Set env Memory for each bot
 *   6. Set env roomStatus and accessibleRooms
 *   7. Truncate roomHistory (past is gone after restore)
 *   8. Update report.ticksRun (if extras.report)
 *
 * @param {StorageAdapter} adapter
 * @param {Object<string, {id:string}>} bots — map of username → { id }
 * @param {Object} snapshot — previously saved snapshot from collectFullDump
 * @param {Object} [extras]
 * @param {Object} [extras.report] — worker report to update ticksRun
 * @returns {Promise<{tick:number, rooms:number, bots:number}>}
 */
async function restoreFromDump(adapter, bots, snapshot, extras = {}) {
    const { db, env } = adapter;

    // 1. Clear and restore rooms.objects
    await clearAndRefill(db['rooms.objects'], snapshot.db['rooms.objects'], 'rooms.objects');

    // 2. Restore terrain (clear + insert, in case terrain changed)
    if (db['rooms.terrain']) {
        await clearAndRefill(db['rooms.terrain'], snapshot.db['rooms.terrain'] || [], 'rooms.terrain');
    }

    // 3. Restore flags
    if (db['rooms.flags'] && snapshot.db['rooms.flags']) {
        await clearAndRefill(db['rooms.flags'], snapshot.db['rooms.flags'], 'rooms.flags');
    }

    // 4. Restore gameTime
    await env.set(env.keys.GAMETIME, String(snapshot.env.gameTime));

    // 5. Restore Memory
    for (const [username, bot] of Object.entries(bots)) {
        const mem = snapshot.env.memory[username];
        if (mem !== undefined) {
            await env.set(env.keys.MEMORY + bot.id, JSON.stringify(mem));
        }
    }

    // 6. Restore roomStatus
    if (snapshot.env.roomStatus) {
        await env.set(env.keys.ROOM_STATUS_DATA, JSON.stringify(snapshot.env.roomStatus));
    }
    if (snapshot.env.accessibleRooms) {
        await env.set(env.keys.ACCESSIBLE_ROOMS, JSON.stringify(snapshot.env.accessibleRooms));
    }

    // 7. Truncate roomHistory (past is gone after restore)
    for (const roomName of snapshot.meta.rooms) {
        try {
            await env.del(env.keys.ROOM_HISTORY + roomName);
        } catch {
            /* roomHistory may not exist — ignore */
        }
    }

    // 8. Update worker state
    if (extras.report) {
        extras.report.ticksRun = snapshot.env.gameTime;
        extras.report.stopReason = null;
    }

    return {
        tick: snapshot.env.gameTime,
        rooms: snapshot.meta.rooms.length,
        bots: Object.keys(bots).length,
    };
}

module.exports = { collectFullDump, restoreFromDump, clearAndRefill };
