'use strict';

/**
 * @file Engine snapshot compatibility guard.
 *
 * Responsibility:
 *   `@screeps/driver` ships a prebuilt V8 snapshot (`build/runtime.snapshot.bin`)
 *   that only works with the exact V8 build it was created with. After a
 *   Node.js upgrade (even a patch release) the engine child processes crash
 *   (Windows) or hang the mock server forever (POSIX). This module
 *   regenerates the snapshot on demand with the official
 *   `make-runtime-snapshot.js` script bundled inside `@screeps/driver`,
 *   guarded by a stamp file and serialised through a lock file so parallel
 *   scenario workers never regenerate concurrently.
 *
 * **Available functions:**
 * - `ensureEngineSnapshotCompat` — regenerates the snapshot when the current
 *   Node/V8 version does not match the stamp file
 * - `resolveDriverDir` — resolves the installed `@screeps/driver` directory
 *
 * The CLI runner (`bin/screeps-integration-tests.js`) calls this eagerly,
 * once per run, before forking scenario workers. `prepareServer` keeps the
 * same call as an idempotent safety net for direct `createWorld` usage
 * outside the CLI (fast path: a single stamp-file read).
 *
 * @module lib/runtime/engineSnapshot
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { FrameworkError } = require('../errors');

/** @type {string} Snapshot blob regenerated by the vendor script */
const SNAPSHOT_FILE = 'runtime.snapshot.bin';
/** @type {string} JSON stamp recording which Node/V8 created the snapshot */
const STAMP_FILE = 'runtime.snapshot.stamp.json';
/** @type {string} Lock file serialising concurrent regeneration */
const LOCK_FILE = 'runtime.snapshot.lock';
/** @type {string} Vendor script bundled with @screeps/driver */
const MAKE_SNAPSHOT_SCRIPT = 'make-runtime-snapshot.js';

/** @type {number} Default spawnSync timeout for the vendor script */
const DEFAULT_TIMEOUT_MS = 120000;
/** @type {number} Poll interval while waiting for another process's lock */
const LOCK_POLL_INTERVAL_MS = 50;

// SharedArrayBuffer-based sleep so that waiting for a concurrent
// regeneration does not require async machinery — keeps the lock protocol
// simple and synchronous for all callers.
const sleepState = new Int32Array(new SharedArrayBuffer(4));

/**
 * Blocks the current thread for the given number of milliseconds.
 *
 * @param {number} ms
 * @returns {void}
 */
function sleepSync(ms) {
    Atomics.wait(sleepState, 0, 0, ms);
}

/**
 * Version stamp of the current Node.js runtime.
 *
 * @returns {{node: string, v8: string, modules: string}}
 */
function currentStamp() {
    return {
        node: process.version,
        v8: process.versions.v8,
        modules: process.versions.modules,
    };
}

/**
 * Resolves the installed `@screeps/driver` package directory.
 *
 * @returns {string}
 */
function resolveDriverDir() {
    return path.dirname(require.resolve('@screeps/driver/package.json'));
}

/**
 * Whether the stored stamp matches the current Node/V8 runtime.
 *
 * @param {string} stampPath
 * @returns {boolean}
 */
function stampMatches(stampPath) {
    try {
        const stored = JSON.parse(fs.readFileSync(stampPath, 'utf8'));
        const current = currentStamp();
        return stored.node === current.node && stored.v8 === current.v8 && stored.modules === current.modules;
    } catch {
        return false;
    }
}

/**
 * Regenerates the engine snapshot by running the vendor script.
 *
 * @param {string} driverDir — @screeps/driver package directory
 * @param {number} timeoutMs — spawnSync timeout
 * @returns {void}
 * @throws {FrameworkError} on missing script, script failure, or missing output
 */
function regenerateSnapshot(driverDir, timeoutMs) {
    const makeScript = path.join(driverDir, MAKE_SNAPSHOT_SCRIPT);
    if (!fs.existsSync(makeScript)) {
        throw new FrameworkError('ENGINE_SNAPSHOT_MISMATCH', driverDir, {}, [
            `The snapshot generator ${makeScript} is missing from the installed @screeps/driver package.`,
            'Reinstall dependencies with `npm ci` and try again.',
        ]);
    }

    const result = spawnSync(process.execPath, [makeScript], {
        cwd: driverDir,
        encoding: 'utf8',
        timeout: timeoutMs,
    });

    if (result.error) {
        throw new FrameworkError('ENGINE_SNAPSHOT_MISMATCH', driverDir, {}, [
            `Failed to run the snapshot generator: ${result.error.message}`,
            'Reinstall dependencies with `npm ci` and try again.',
        ]);
    }

    if (result.status !== 0) {
        const stdout = (result.stdout || '').trim();
        const stderr = (result.stderr || '').trim();
        throw new FrameworkError(
            'ENGINE_SNAPSHOT_MISMATCH',
            driverDir,
            {},
            [
                `The snapshot generator exited with code ${result.status}.`,
                stdout ? `stdout: ${stdout}` : '',
                stderr ? `stderr: ${stderr}` : '',
                'Reinstall dependencies with `npm ci` and try again.',
            ].filter(Boolean),
        );
    }

    const snapshotPath = path.join(driverDir, 'build', SNAPSHOT_FILE);
    if (!fs.existsSync(snapshotPath)) {
        throw new FrameworkError('ENGINE_SNAPSHOT_MISMATCH', driverDir, {}, [
            `The snapshot generator completed, but ${snapshotPath} was not created.`,
            'Reinstall dependencies with `npm ci` and try again.',
        ]);
    }
}

/**
 * Ensures the `@screeps/driver` engine snapshot matches the current Node/V8
 * version. Regenerates it (via the vendor script) when the stamp does not
 * match, and serialises concurrent regeneration between worker processes
 * with a lock file.
 *
 * Fast path: a matching stamp plus an existing snapshot is a no-op
 * (a single file read per `createWorld` call).
 *
 * @param {Object} [opts]
 * @param {string} [opts.driverDir] — override for tests (defaults to the
 *   installed @screeps/driver package directory)
 * @param {number} [opts.timeoutMs] — regeneration timeout (default 120000)
 * @returns {void}
 * @throws {FrameworkError}
 */
function ensureEngineSnapshotCompat(opts = {}) {
    const driverDir = opts.driverDir || resolveDriverDir();
    const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;

    const buildDir = path.join(driverDir, 'build');
    const snapshotPath = path.join(buildDir, SNAPSHOT_FILE);
    const stampPath = path.join(buildDir, STAMP_FILE);
    const lockPath = path.join(buildDir, LOCK_FILE);

    // Fast path: the snapshot was already generated by this exact runtime.
    if (fs.existsSync(snapshotPath) && stampMatches(stampPath)) {
        return;
    }

    // Serialise regeneration across worker processes.
    let fd;
    try {
        fd = fs.openSync(lockPath, 'wx');
        fs.writeSync(fd, String(process.pid));
    } catch (e) {
        if (e.code !== 'EEXIST') {
            throw e;
        }
        // Another process is regenerating. Wait for its stamp to appear.
        const deadline = Date.now() + timeoutMs;
        while (Date.now() < deadline) {
            if (fs.existsSync(snapshotPath) && stampMatches(stampPath)) {
                return;
            }
            sleepSync(LOCK_POLL_INTERVAL_MS);
        }
        throw new FrameworkError('ENGINE_SNAPSHOT_MISMATCH', lockPath, {}, [
            'Timed out waiting for another process to regenerate the engine snapshot.',
            `Delete the stale lock file (${lockPath}) and run again.`,
        ]);
    }

    try {
        if (fs.existsSync(snapshotPath) && stampMatches(stampPath)) {
            // Another worker finished while we were acquiring the lock.
            return;
        }
        const stamp = currentStamp();
        console.log(
            `[engineSnapshot] Node.js ${stamp.node} (V8 ${stamp.v8}) differs from the snapshot build — ` +
                'regenerating the engine snapshot (this can take a while)...',
        );
        regenerateSnapshot(driverDir, timeoutMs);
        fs.writeFileSync(stampPath, `${JSON.stringify(stamp, null, 2)}\n`);
    } finally {
        if (fd !== undefined) {
            fs.closeSync(fd);
        }
        try {
            fs.unlinkSync(lockPath);
        } catch {
            // Lock already gone — nothing to clean up.
        }
    }
}

module.exports = { ensureEngineSnapshotCompat, resolveDriverDir, SNAPSHOT_FILE, STAMP_FILE };
